#!/usr/bin/env python3
"""Generate the canonical series-name catalog the EPUB importer matches against.

NOT shipped in the app. Run on a dev machine (or CI) to refresh the bundled
catalog; the app only ever reads the resulting .txt from assets.

Source: the AniList GraphQL API (https://anilist.co) — free, no API key,
clean English/romaji titles for manga and light novels, sortable by
popularity. We take the most popular `--pages` x 50 series, prefer the English
title when present, dedupe case-insensitively, and write one name per line.

The bundled list is only a *seed*: the app grows its own overlay as the user
confirms/adds names, so it doesn't need to be exhaustive.

Usage:
    python3 tools/generate_catalog.py [--pages 50] [--out app/src/main/assets/catalog/series.txt]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request

API_URL = "https://graphql.anilist.co"

QUERY = """
query ($page: Int, $perPage: Int) {
  Page(page: $page, perPage: $perPage) {
    pageInfo { hasNextPage }
    media(type: MANGA, sort: POPULARITY_DESC) {
      title { english romaji }
    }
  }
}
"""


def fetch_page(page: int, per_page: int) -> dict:
    body = json.dumps({"query": QUERY, "variables": {"page": page, "perPage": per_page}}).encode()
    req = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            # Some egress proxies reject the default urllib UA with a 403.
            "User-Agent": "Mozilla/5.0 (mipuble-catalog-generator)",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def collect(pages: int, per_page: int) -> list[str]:
    seen: dict[str, str] = {}  # lowercase key -> first-seen display name
    for page in range(1, pages + 1):
        for attempt in range(5):
            try:
                payload = fetch_page(page, per_page)
                break
            except urllib.error.HTTPError as e:
                # 429 = rate limited; back off and retry.
                wait = int(e.headers.get("Retry-After", 2 ** attempt))
                print(f"  page {page}: HTTP {e.code}, waiting {wait}s", file=sys.stderr)
                time.sleep(wait)
            except urllib.error.URLError as e:
                print(f"  page {page}: {e}, retrying", file=sys.stderr)
                time.sleep(2 ** attempt)
        else:
            print(f"  page {page}: giving up after retries", file=sys.stderr)
            continue

        data = payload.get("data", {}).get("Page", {})
        for media in data.get("media", []):
            title = media.get("title") or {}
            name = (title.get("english") or title.get("romaji") or "").strip()
            if not name:
                continue
            key = name.lower()
            seen.setdefault(key, name)

        print(f"  page {page}: {len(seen)} unique so far", file=sys.stderr)
        if not data.get("pageInfo", {}).get("hasNextPage", False):
            break
        time.sleep(0.8)  # stay well under AniList's ~90 req/min limit

    return sorted(seen.values(), key=str.casefold)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pages", type=int, default=50, help="pages of 50 to fetch (default 50 = 2500 series)")
    parser.add_argument("--per-page", type=int, default=50, help="AniList caps this at 50")
    parser.add_argument(
        "--out",
        default=os.path.join("app", "src", "main", "assets", "catalog", "series.txt"),
    )
    args = parser.parse_args()

    print(f"Fetching up to {args.pages * args.per_page} popular series from AniList…", file=sys.stderr)
    names = collect(args.pages, min(args.per_page, 50))
    if not names:
        print("No names fetched — aborting so an empty catalog isn't committed.", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    header = (
        "# Canonical series names for mipuble's importer.\n"
        "# Generated by tools/generate_catalog.py from AniList; do not hand-edit —\n"
        "# add names in-app instead (they go to the writable user overlay).\n"
        "# One series per line; blank lines and lines starting with # are ignored.\n"
    )
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(header)
        for name in names:
            f.write(name + "\n")

    print(f"Wrote {len(names)} series to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
